lobot:
  left_arm_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
    pid: {p: 20, i: 0.3, d: 5, i_min: -100, i_max: 100, antiwindup: True}
  joint_1_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_1_joint
    pid: {p: 70, i: 2, d: 5.0, i_min: -180, i_max: 180, antiwindup: True}
  joint_2_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_2_joint
    pid: {p: 5, i: 0.2, d: 5, i_min: -30, i_max: 30, antiwindup: True}
  joint_3_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_3_joint
    pid: {p: 4, i: 0.2, d: 0.5, i_min: -30, i_max: 30, antiwindup: True}
  joint_4_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_4_joint
    pid: {p: 50, i: 3 , d: 6.0, i_min: -10, i_max: 10, antiwindup: True}
  joint_5_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_5_joint
    pid: {p: 8, i: 0.3, d: 1.2, i_min: -10, i_max: 10, antiwindup: True}