lobot:
  left_arm_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
    pid: {p: 4, i: 0.05, d: 0.15, i_min: -2, i_max: 2, antiwindup: True}  
  left_arm_controller_3:
    type: "ros_controllers::JointPositionController"
    joints:
      - arm_left_3_joint
    pid: {p: 4, i: 0.05, d: 0.15, i_min: -2, i_max: 2, antiwindup: True}
  joint_1_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_1_joint
    pid: {p: 4, i: 0.05, d: 0.15, i_min: -4, i_max: 4, antiwindup: True}
  joint_2_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_2_joint
    pid: {p: 4, i: 0.05, d: 0.15, i_min: -3, i_max: 3, antiwindup: True}
  joint_3_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_3_joint
    pid: {p: 4, i: 0.05, d: 0.15, i_min: -3, i_max: 3, antiwindup: True}
  joint_4_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_4_joint
    pid: {p: 4, i: 0 , d: 0.15, i_min: -3, i_max: 3, antiwindup: True}
  joint_5_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_left_5_joint
      - leg_right_5_joint
    pid: {p: 4, i: 0, d: 0.15, i_min: -3, i_max: 3, antiwindup: True}