lobot:
  # joint_state_controller:
  #   type: "ros_controllers::JointStateController"
  #   joints:
  #     - leg_right_1_joint
  #     - leg_right_2_joint
  #     - leg_right_3_joint
  #     - leg_right_4_joint
  #     - leg_right_5_joint
  #     - leg_left_1_joint
  #     - leg_left_2_joint
  #     - leg_left_3_joint
  #     - leg_left_4_joint
  #     - leg_left_5_joint
  #     - arm_right_1_joint
  #     - arm_right_2_joint
  #     - arm_right_3_joint
  #     - arm_left_1_joint
  #     - arm_left_2_joint
  #     - arm_left_3_joint
  joint_position_controller:
    type: "ros_controllers::JointPositionController"
    joints:
      - leg_right_1_joint
      - leg_right_2_joint
      - leg_right_3_joint
      - leg_right_4_joint
      - leg_right_5_joint
      - leg_left_1_joint
      - leg_left_2_joint
      - leg_left_3_joint
      - leg_left_4_joint
      - leg_left_5_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint


